Added support for multiline secrets and vars

diff --git a/.github/workflows/prepare-pipeline.yml b/.github/workflows/prepare-pipeline.yml
--- a/.github/workflows/prepare-pipeline.yml
+++ b/.github/workflows/prepare-pipeline.yml
@@ -43,34 +43,33 @@ jobs:
 
           while IFS= read -r env_var; do
               export $env_var
-          done < <(echo $SECRETS_CONTEXT | jq -r 'to_entries| .[] | .key + "=\"" + (.value|tostring) + "\""')
+          done < <(echo $SECRETS_CONTEXT | jq -r 'to_entries | .[] | .key + "=\"" + (.value | gsub("\r\n|\n|\r"; "")) + "\""')
 
           while IFS= read -r env_var; do
               export $env_var
-          done < <(echo $VARS_CONTEXT | jq -r 'to_entries| .[] | .key + "=\"" + (.value|tostring) + "\""')
+          done < <(echo $VARS_CONTEXT | jq -r 'to_entries | .[] | .key + "=\"" + (.value | gsub("\r\n|\n|\r"; "")) + "\""')
 
           if [[ -f .env.example ]]; then
-              while IFS= read -r line || [[ -n "$line" ]]; do
-              if [[ "$line" == *'='* && "$line" != '#'* ]]; then
-                  required_variables+=("$(echo "$line" | cut -d '=' -f 1)")
-              fi
-              done < ".env.example"
+            while IFS= read -r line || [[ -n "$line" ]]; do
+            if [[ "$line" == *'='* && "$line" != '#'* ]]; then
+              required_variables+=("$(echo "$line" | cut -d '=' -f 1)")
+            fi
+            done < ".env.example"
           fi
 
           missing_variables=()
 
           for var in "${required_variables[@]}"; do
-              if [[ -z ${!var} ]]; then
-                  echo $var
-                  missing_variables+=($var)
-              fi
+            if [[ -z ${!var} ]]; then
+              missing_variables+=($var)
+            fi
           done
 
           if [[ ${#missing_variables[@]} -gt 0 ]]; then
-              for var in "${missing_variables[@]}"; do
-                  echo "Missing \"$var\" variable"
-              done
-              exit 1
+            for var in "${missing_variables[@]}"; do
+              echo "Missing \"$var\" variable"
+            done
+            exit 1
           fi
 
           echo "PROJECT_TYPE=$PROJECT_TYPE"
