Added required variables and parsing of .env.example

diff --git a/.github/workflows/prepare-pipeline.yml b/.github/workflows/prepare-pipeline.yml
--- a/.github/workflows/prepare-pipeline.yml
+++ b/.github/workflows/prepare-pipeline.yml
@@ -29,28 +29,42 @@ jobs:
 
       - name: Validate required variables
         id: required-vars
+        env:
+          SECRETS_CONTEXT: ${{ toJson(secrets) }}
+          VARS_CONTEXT: ${{ toJson(vars) }}
         run: |
-          echo $ALLMYSECRETS
-          echo $ALLMYVARS
+          required_variables=(PROJECT_TYPE)
 
-          require_variables=("PROJECT_TYPE")
+          while IFS= read -r env_var; do
+              export $env_var
+          done < <(echo $SECRETS_CONTEXT | jq -r 'to_entries| .[] | .key + "=\"" + (.value|tostring) + "\""')
+
+          while IFS= read -r env_var; do
+              export $env_var
+          done < <(echo $VARS_CONTEXT | jq -r 'to_entries| .[] | .key + "=\"" + (.value|tostring) + "\""')
+
+          if [[ -f .env.example ]]; then
+              while IFS= read -r line || [[ -n "$line" ]]; do
+              if [[ "$line" == *'='* && "$line" != '#'* ]]; then
+                  required_variables+=("$(echo "$line" | cut -d '=' -f 1)")
+              fi
+              done < ".env.example"
+          fi
 
           missing_variables=()
 
-          for var in "${require_variables[@]}"; do
+          for var in "${required_variables[@]}"; do
               if [[ -z ${!var} ]]; then
-                missing_variables+=($var)
-              else
-                echo "$var=${!var}"
-                echo "$var=${!var}" >> $GITHUB_OUTPUT
+                  echo $var
+                  missing_variables+=($var)
               fi
           done
 
           if [[ ${#missing_variables[@]} -gt 0 ]]; then
-            for var in "${missing_variables[@]}"; do
-              echo "Missing $var variable"
-            done
-            exit 1
+              for var in "${missing_variables[@]}"; do
+                  echo "Missing \"$var\" variable"
+              done
+              exit 1
           fi
 
           echo "PROJECT_TYPE=$PROJECT_TYPE"
@@ -98,6 +112,10 @@ jobs:
           echo "### Prepare pipeline:               
           <table>
             <tr>
+              <td>💡 Project type</td>
+              <td>${{ steps.required-vars.outputs.PROJECT_TYPE }}</td>
+            </tr>
+            <tr>
               <td>🚀 Deployment platform</td>
               <td>${{ steps.deploy-platform.outputs.DEPLOY_PLATFORM }}</td>
             </tr>
@@ -110,18 +128,6 @@ jobs:
               <td>${{ steps.image-name.outputs.IMAGE_NAME }}</td>
             </tr>
           </table>" >> $GITHUB_STEP_SUMMARY
-
-  prepare-env:
-    needs: prepare-variables
-    runs-on: ubuntu-latest
-
-    environment: ${{ needs.prepare-variables.outputs.DEPLOY_ENV }}
-  
-    steps:
-      - name: Prepare environment
-        run: |
-          echo "Prepare environment for $DEPLOY_ENV"
-          echo "Prepare environment for $DEPLOY_ENV" >> $GITHUB_OUTPUT
 
   prepare-azure:
     if: |
